- name: Debug entry into backup.yml
  debug:
    msg: "Starting tasks in backup.yml"
- name: Backup running config
  ios_command:
    commands:
      - show running-config
  register: running_config

- name: Save running config to file
  copy:
    content: "{{ running_config.stdout[0] }}"
    dest: "backup/{{ lookup('pipe', 'date +%Y-%m-%d') }}/{{ inventory_hostname }}_backup.cfg"

- name: Backup config and prepare for update if needed
  include_tasks: check_space.yml
  when: update_needed | bool